name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "First Command"
          echo "Second Command"
      - name: Print Goodbye
        run: echo "Done - Bye!"
  
